"""initial

Revision ID: 3b4fff9f2e3f
Revises: 
Create Date: 2025-10-06 18:14:16.694592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4fff9f2e3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_number', sa.String(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('industrial_flag', sa.String(), nullable=True),
    sa.Column('purchase_department', sa.String(), nullable=True),
    sa.Column('purchase_expert', sa.String(), nullable=True),
    sa.Column('applicant', sa.String(), nullable=True),
    sa.Column('applicant_company', sa.String(), nullable=True),
    sa.Column('applicant_unit', sa.String(), nullable=True),
    sa.Column('consumer_company', sa.String(), nullable=True),
    sa.Column('consumer_unit', sa.String(), nullable=True),
    sa.Column('latest_status', sa.String(), nullable=True),
    sa.Column('winning_source', sa.String(), nullable=True),
    sa.Column('date_request', sa.String(), nullable=True),
    sa.Column('date_mrs', sa.String(), nullable=True),
    sa.Column('date_entry', sa.String(), nullable=True),
    sa.Column('purchase_duration', sa.String(), nullable=True),
    sa.Column('initial_amount', sa.Float(), nullable=True),
    sa.Column('currency_unit', sa.String(), nullable=True),
    sa.Column('order_amount', sa.Float(), nullable=True),
    sa.Column('order_currency', sa.String(), nullable=True),
    sa.Column('extra_cost_rial', sa.Float(), nullable=True),
    sa.Column('converted_cost_rial', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('date_start', sa.String(), nullable=True),
    sa.Column('date_end', sa.String(), nullable=True),
    sa.Column('urgency_code', sa.String(), nullable=True),
    sa.Column('date_order', sa.String(), nullable=True),
    sa.Column('first_item_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_requests_latest_status'), ['latest_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_requests_purchase_department'), ['purchase_department'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_requests_purchase_expert'), ['purchase_expert'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_requests_request_number'), ['request_number'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('field_changed', sa.String(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('change_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['purchase_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('purchase_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_requests_request_number'))
        batch_op.drop_index(batch_op.f('ix_purchase_requests_purchase_expert'))
        batch_op.drop_index(batch_op.f('ix_purchase_requests_purchase_department'))
        batch_op.drop_index(batch_op.f('ix_purchase_requests_latest_status'))

    op.drop_table('purchase_requests')
    # ### end Alembic commands ###
